### ISSUE TITLE
WDK11

### ISSUE THREAD

**Issue by willhughes-au** [nioncode/Chocolatey-WDK10#6]
Hi there, 

I need WDK11 for an internal project, so I hope you don't mind that I forked this repository and made the applicable modifications. 

You can see my fork here: https://github.com/willhughes-au/Chocolatey-WDK11 

I've kept your name on the license file, and I'm currently waiting on the package to be moderated by Chocolatey at https://community.chocolatey.org/packages/windowsdriverkit11/10.0.22000.1 

Feel free to reach out if you've got any questions/concerns. 

Cheers,
Will.

**Comment by nioncode** [comment]
Sounds good! Feel free to ping me if you make any important changes (maybe because the setup routine of wdk changes or whatever).
